name: Build mtdt_simple softwares for all systems

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            os_short_name: win
            ext: .exe
            sep: ";"
            arch: x64
          - os: windows-latest
            os_short_name: win
            ext: .exe
            sep: ";"
            arch: x86
          - os: ubuntu-latest
            os_short_name: linux
            ext: ""
            sep: ":"
            arch: x64
          - os: ubuntu-24.04-arm
            os_short_name: linux
            ext: ""
            sep: ":"
            arch: arm64
          - os: macos-latest
            os_short_name: mac
            ext: ""
            sep: ":"
            arch: arm64
          
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        # xיתקין פייתון שמתאים לארכיטקטורה הספציפית. בלי השורה הבאה זה יהיה 64
        architecture: ${{ matrix.arch }} 
        #cache: pip
        #cache-dependency-path: .github/workflows/build_cu_for_all_systems.yml

    - name: Install yda common dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow clipboard

    - name: Install Linux packaging tools
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev fakeroot
        #pip install appimage-builder
    
    
    # ---- Build ONEDIR first ----
    - name: Build onedir
      shell: bash
      run: |
        
        OS="${{ matrix.os }}"
        VERSION="${{ matrix.os_short_name }}_${{ matrix.arch }}_onedir"
        MAIN_FILE="yDNA_tool.py"
        APP_NAME="yDNA_tool"

        ##########################################################
        # הכנת הקבצים הנוספים שצריך להוסיף לתיקיית ההתקנה
        COMMON_DATA="\
        --add-data required_files/RSRS.txt${{ matrix.sep }}. \
        --add-data required_files/rCRS.txt${{ matrix.sep }}. 
        "

        # עכשיו פקודת ייצוא קובץ ההתקנה
        pyinstaller --noconsole --name $APP_NAME $COMMON_DATA $MAIN_FILE

        ##########################################################################
        
        # יוצרים עותק של תיקיית הגרסה
        cp -r dist/$APP_NAME ${APP_NAME}_${VERSION}
        
        # יוצרים תיקיית ריליס אם איננה קיימת
        mkdir -p release
        
        # דוחסים את כל התיקייה כיחידה אחת (לא רק את התוכן שלה)
        python -m zipfile -c release/${APP_NAME}_${VERSION}.zip ${APP_NAME}_${VERSION}
        
        # מוחקים את תיקיית הגרסה
        rm -rf ${APP_NAME}_${VERSION}

        # הכנת הקובץ של mtDNA_tool עבור onefile
        # מתקין עושים רק לגרסת ווינדוס האחרונה
        if [ "$OS" = "windows-latest" ]; then
          cp dist/$APP_NAME/$APP_NAME.exe required_files/${APP_NAME}_dir.exe
        else
          cp dist/${APP_NAME}/${APP_NAME} required_files/${APP_NAME}_dir
        fi

       

    # ---- Build Windows Installer (Inno Setup) ----
    - name: Create setup.iss
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        APP_NAME="mtDNA_tool_simple"
        ARCH="${{ matrix.arch }}"   # הגדרת שם הארכיטקטורה
        
        echo "#define AppName \"$APP_NAME\"" > setup.iss
        echo '' >> setup.iss
        echo '[Setup]' >> setup.iss
        echo 'AppName={#AppName}' >> setup.iss
        echo 'AppVersion=1.0' >> setup.iss
        echo 'DefaultDirName={commonpf}\{#AppName}' >> setup.iss
        echo "OutputBaseFilename=${APP_NAME}_win_${ARCH}_installer" >> setup.iss
        echo 'OutputDir=installer' >> setup.iss
        echo 'Compression=lzma' >> setup.iss
        echo 'SolidCompression=yes' >> setup.iss
        echo 'CreateAppDir=yes' >> setup.iss
        echo 'DisableProgramGroupPage=no' >> setup.iss
        echo 'DefaultGroupName={#AppName}' >> setup.iss
        echo '' >> setup.iss
        echo '[Languages]' >> setup.iss
        echo 'Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"' >> setup.iss
        echo 'Name: "english"; MessagesFile: "compiler:Default.isl"' >> setup.iss
        echo '' >> setup.iss
        echo '[Files]' >> setup.iss
        echo 'Source: "dist\'"$APP_NAME"'\'"$APP_NAME"'.exe"; DestDir: "{app}"; Flags: ignoreversion' >> setup.iss
        echo 'Source: "dist\'"$APP_NAME"'\_internal\*"; DestDir: "{app}\_internal"; Flags: recursesubdirs ignoreversion' >> setup.iss
        echo '' >> setup.iss
        echo '[Icons]' >> setup.iss
        echo 'Name: "{commondesktop}\{#AppName}"; Filename: "{app}\'"$APP_NAME"'.exe"' >> setup.iss
        echo 'Name: "{group}\{#AppName}"; Filename: "{app}\'"$APP_NAME"'.exe"' >> setup.iss
        echo '' >> setup.iss
        echo '[Run]' >> setup.iss
        echo 'Filename: "{app}\'"$APP_NAME"'.exe"; Description: "Run {#AppName}"; Flags: nowait postinstall skipifsilent' >> setup.iss

    - name: Install Inno Setup
      if: matrix.os == 'windows-latest'
      run: choco install innosetup -y

    - name: Build Installer
      if: matrix.os == 'windows-latest'
      run: iscc setup.iss

    - name: Add Installer to Release folder
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        ARCH="${{ matrix.arch }}"   # הגדרת שם הארכיטקטורה
        mkdir -p release
        cp installer/*.exe release/ # מחפש קובץ שמסתיים ב EXE ומוסיף אותו

    
    # מוחקים את תיקיות הבנייה כדי שיהיו מוכנות ריקות לבנייה הבאה של תוכנה בקובץ אחד
    - name: Clean build directories
      shell: bash
      run: rm -rf build dist

    # ---- Build ONEFILE ----
    - name: Build onefile
      shell: bash
      run: |
      
        OS="${{ matrix.os }}"
        VERSION="${{ matrix.os_short_name }}_${{ matrix.arch }}_onefile"
        MAIN_FILE="yDNA_tool.py"
        APP_NAME="yDNA_tool"

        ##########################################################
        # הכנת הקבצים הנוספים שצריך להוסיף לתיקיית ההתקנה
        COMMON_DATA="\
        --add-data required_files/RSRS.txt${{ matrix.sep }}. \
        --add-data required_files/rCRS.txt${{ matrix.sep }}. 
        "

        # עכשיו פקודת ייצוא קובץ ההתקנה
        pyinstaller --noconsole --name $APP_NAME --onefile $COMMON_DATA $MAIN_FILE

        ##########################################################################
      
        mkdir -p release
        cp dist/${APP_NAME}${{ matrix.ext }} release/${APP_NAME}_${VERSION}${{ matrix.ext }}

    
    - name: Upload all builds to release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: auto-build
        files: release/*
        overwrite_files: true                      # מחליף קבצים קיימים עם אותו שם

    
